name: Marvela
description: A marvel character application.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  google_fonts: ^3.0.1
  hydrated_bloc: ^9.0.0-dev.3
  json_annotation: ^4.4.0
  path_provider: ^2.0.8
  marvel_repository:
    path: packages/marvel_repository
  favorites_repository:
    path: packages/favorites_repository
  local_storage_favorites_api:
    path: packages/local_storage_favorites_api
  bloc_concurrency: ^0.2.0
  stream_transform: ^2.0.1
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.2

flutter:
  uses-material-design: true
  # assets:
  # - assets/
