name: marvel_api
description: A Dart API Client for the Marvel API.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  crypto: ^3.0.2
  http: ^0.13.0
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  test: ^1.16.4
  very_good_analysis: ^3.0.2
  flutter_lints: ^2.0.0
  envied_generator: ^0.2.3
